### ISSUE TITLE
Provide a Sass mixin that includes all 4 required CSS properties

### ISSUE THREAD

**Issue by agrobbin** [agrobbin/spritely#16]
Currently if you want to use a sprited image in CSS, you have to call 4 different functions in your Sass/Scss file:

```scss
#icon {
  background: {
    image: spritely-url("application");
    position: spritely-position("application", "icon");
  }
  width: spritely-width("application", "icon");
  height: spritely-height("application", "icon");
}
```

This is a very common occurrence, and could stand to be simplified by providing 1 mixin that does all of this for us, resulting in something akin to:

```scss
#icon {
  @include spritely-image("application", "icon");
}
```
